#pragma once

#include "operator/rns_layout.hpp"

#include <cstdint>
#include <string>

namespace hpu::scheme::ckks {

// Rotate a two-component ciphertext already in canonical HPU NTT order.
// p3 loads in the first phase must bind the modified-root tables generated by
// hpu::seal_adapter::create_fused_inverse_automorphism_tables.
std::string generate_rotate_body_asm(
    int N,
    const hpu::RnsDecompositionLayout& layout,
    std::uint32_t galois_element,
    bool append_psync = true);

// High-level CKKS entry points. Positive slot steps rotate left, negative
// steps rotate right. They map to a raw Galois element and reuse the same
// modified-root fused INTT/KeySwitch implementation above.
std::string generate_rotate_steps_body_asm(
    int N,
    const hpu::RnsDecompositionLayout& layout,
    int steps,
    bool append_psync = true);

std::string generate_conjugate_body_asm(
    int N,
    const hpu::RnsDecompositionLayout& layout,
    bool append_psync = true);

std::string generate_rotate_body_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    std::uint32_t galois_element,
    bool append_psync = true);

std::string generate_rotate_steps_body_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    int steps,
    bool append_psync = true);

std::string generate_conjugate_body_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    bool append_psync = true);

std::string generate_rotate_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    std::uint32_t galois_element,
    bool append_psync = true);

std::string generate_rotate_steps_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    int steps,
    bool append_psync = true);

std::string generate_conjugate_asm(
    int N,
    int num_q,
    int num_p,
    int dnum,
    bool append_psync = true);

} // namespace hpu::scheme::ckks
