#pragma once

#include "hpu/runtime/memory_image.hpp"
#include "instruction.hpp"

#include <seal/seal.h>

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace hpu::seal_adapter {

struct BgvKeySwitchDmaBinding {
    std::size_t dma_index = 0;
    std::size_t instruction_index = 0;
    hpu::Mnemonic direction = hpu::Mnemonic::kDload;
    std::uint8_t object_slot = 0;
    std::uint8_t type_or_release = 0;
    std::uint8_t flag = 0;
    std::string allocation_id;
    hpu::runtime::HpuMemSpan span;
    std::optional<std::size_t> operation_index;
    std::string operation_id = "$application";
    std::size_t operation_dma_index = 0;
};

// Resolved single-operation BGV image/DMA container, also reused by the
// pointwise arithmetic and Galois rotation applications. No SecretKey enters
// the image.
struct BgvKeySwitchApplication {
    hpu::runtime::HpuMemImage image;
    ::seal::parms_id_type parms_id{};
    std::uint64_t correction_factor = 1;
    std::vector<hpu::EncodedInstruction> instructions;
    std::vector<BgvKeySwitchDmaBinding> dma;

    std::vector<hpu::runtime::HpuMemSpan> spans() const;
};

struct BgvKeySwitchRuntimeArtifacts {
    std::string header;
    std::string source;
    std::string resolved_dma_manifest;
};

// Exact line count of the current all-resident image layout. This is a
// software allocation estimate, not a guarantee of physical window support.
std::uint64_t estimate_bgv_keyswitch_image_lines(
    std::size_t degree,
    std::size_t active_q_count,
    std::size_t key_modulus_count);

// Adds four read-only input limbs per active Q to the KeySwitch image; the
// three tensor components reuse its mutable input/c* allocations.
std::uint64_t estimate_bgv_multiply_relinearize_image_lines(
    std::size_t degree,
    std::size_t active_q_count,
    std::size_t key_modulus_count);

std::uint64_t estimate_bgv_rotation_image_lines(
    std::size_t degree, std::size_t active_q_count,
    std::size_t key_modulus_count);

BgvKeySwitchApplication build_bgv_keyswitch_application(
    const ::seal::SEALContext& context,
    const ::seal::Ciphertext& product,
    const ::seal::RelinKeys& relin_keys,
    std::uint64_t capacity_lines);

// Produces one uninterrupted canonical-NTT CMULT + BGV KeySwitch program.
// The three-component tensor product is generated by HPU, never by CPU/SEAL.
BgvKeySwitchApplication build_bgv_multiply_relinearize_application(
    const ::seal::SEALContext& context,
    const ::seal::Ciphertext& left,
    const ::seal::Ciphertext& right,
    const ::seal::RelinKeys& relin_keys,
    std::uint64_t capacity_lines);

// One uninterrupted canonical-NTT automorphism + BGV Galois KeySwitch.
// Rows use nonzero signed steps; columns swap the two batching rows.
BgvKeySwitchApplication build_bgv_rotate_rows_application(
    const ::seal::SEALContext& context, const ::seal::Ciphertext& input,
    const ::seal::GaloisKeys& galois_keys, int steps,
    std::uint64_t capacity_lines);
BgvKeySwitchApplication build_bgv_rotate_columns_application(
    const ::seal::SEALContext& context, const ::seal::Ciphertext& input,
    const ::seal::GaloisKeys& galois_keys,
    std::uint64_t capacity_lines);

BgvKeySwitchRuntimeArtifacts render_bgv_keyswitch_runtime_artifacts(
    const std::string& stem,
    const BgvKeySwitchApplication& application);

} // namespace hpu::seal_adapter
